### PR TITLE
fix: LockerSpawnpoint in CustomItem

### LINKED ISSUE #356: [BUG] Using LockerSpawnPoint in CustomItem causes items not to be picked up.
https://github.com/ExMod-Team/EXILED/blob/f8582274c9168a9b06b6da542953b7540eddde66/EXILED/Exiled.CustomItems/API/Features/CustomItem.cs#L654-L655

If the intention of Pickup.Locked was to emulate the function that the items appear inside the chamber and are unlocked when opening the chamber, they should use the function of the base game or something similar.
```cs
public void SetDoor(bool doorStatus, AudioClip beepClip)
		{
			if (doorStatus == this._prevDoor)
			{
				return;
			}
			this.IsOpen = doorStatus;
			this._prevDoor = doorStatus;
			if (this.AnimatorSet)
			{
				this._animator.SetBool(LockerChamber.DoorHash, doorStatus);
				this._targetCooldown = this._animationTime;
				this._stopwatch.Restart();
			}
			if (!NetworkServer.active)
			{
				Action onDoorStatusSet = this.OnDoorStatusSet;
				if (onDoorStatusSet == null)
				{
					return;
				}
				onDoorStatusSet();
				return;
			}
			else
			{
				if (doorStatus && !this._wasEverOpened)
				{
					this._wasEverOpened = true;
					foreach (ItemPickupBase itemPickupBase in this.Content)
					{
						if (!(itemPickupBase == null))
						{
							PickupSyncInfo info = itemPickupBase.Info;
							info.Locked = false;
							itemPickupBase.NetworkInfo = info;
						}
					}
					if (!this._spawnOnFirstChamberOpening)
					{
						return;
					}
					foreach (ItemPickupBase itemPickupBase2 in this._toBeSpawned)
					{
						if (!(itemPickupBase2 == null))
						{
							ItemDistributor.SpawnPickup(itemPickupBase2);
						}
					}
				}
				Action onDoorStatusSet2 = this.OnDoorStatusSet;
				if (onDoorStatusSet2 == null)
				{
					return;
				}
				onDoorStatusSet2();
				return;
			}
		}
```

### PR DESCRIPTION
**Pull request by SrLicht**
## Description
Fixing the brain-washing of 𝗩𝗔𝗟𝗘𝗥𝗔𝟳𝟳𝟭 in customitem
Closes #356

**What is the current behavior?** (You can also link to an open issue here)
the pickup its locked when spawning in a locker

**What is the new behavior?** (if this is a feature change)
work

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

**Other information**:
I am sleepy

Code test is in the discord bug-report.
<br />

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

### CODE REVIEW

**Review by louis1706 — APPROVED** [review]

**Review by VALERA771 — APPROVED** [review]
Bruh 💀

File: EXILED/Exiled.CustomItems/API/Features/CustomItem.cs [hunk 1]
```diff
@@ -5,6 +5,8 @@
 // </copyright>
 // -----------------------------------------------------------------------
 
+using Exiled.API.Features.Lockers;
```
Comment (VALERA771) [inline EXILED/Exiled.CustomItems/API/Features/CustomItem.cs:8]: Huh?

**Review by VALERA771 — CHANGES_REQUESTED** [review]

**Review by Misfiy — APPROVED** [review]

**Review by VALERA771 — APPROVED** [review]
